{{- if or .Values.standaloneCollector.enabled (eq .Values.mode "deployment") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  cloud-trace-sa: {{.Values.cloudTraceServiceAccount}}
{{- end }}
